### ISSUE TITLE
Using SQLite.WinRT v3.8.11.2 and am getting “too many columns” error when trying to create a table.

### ISSUE THREAD

**Issue by gregbrainerd** [vlechenko/SQLite.WinRT#1]
From what I can find SQLite3 has a command sqlite3_limit(db, limit, val); that can be used to increase the limit from the default of 2000. I am not sure if I can use this command or exactly how I would use it? When I try putting it into the line before I try to create the table it tells me it doesn’t exist. 

https://www.sqlite.org/limits.html
https://www.sqlite.org/c3ref/limit.html

**Comment by vlechenko** [comment]
Please update for 3.8.11.3 and use method SQLiteConnection.SetLimits(id, val).
To see available ids please see constants from class SQLiteLimit

**Comment by gregbrainerd** [comment]
Thank you, I’ll give that a try.
